/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthRouteImport } from './routes/oauth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMypageRouteImport } from './routes/_app/mypage'
import { Route as AppExcellentCasesRouteImport } from './routes/_app/excellent-cases'
import { Route as AppAdminExcellentCasesRouteImport } from './routes/_app/admin-excellent-cases'
import { Route as AppConsultRouteImport } from './routes/_app/_consult'
import { Route as AppConsultSummaryRouteImport } from './routes/_app/_consult/summary'
import { Route as AppConsultConsultationResultRouteImport } from './routes/_app/_consult/consultation-result'
import { Route as AppConsultConsultationListRouteImport } from './routes/_app/_consult/consultation-list'

const OauthRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMypageRoute = AppMypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => AppRoute,
} as any)
const AppExcellentCasesRoute = AppExcellentCasesRouteImport.update({
  id: '/excellent-cases',
  path: '/excellent-cases',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminExcellentCasesRoute = AppAdminExcellentCasesRouteImport.update({
  id: '/admin-excellent-cases',
  path: '/admin-excellent-cases',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultRoute = AppConsultRouteImport.update({
  id: '/_consult',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultSummaryRoute = AppConsultSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppConsultRoute,
} as any)
const AppConsultConsultationResultRoute =
  AppConsultConsultationResultRouteImport.update({
    id: '/consultation-result',
    path: '/consultation-result',
    getParentRoute: () => AppConsultRoute,
  } as any)
const AppConsultConsultationListRoute =
  AppConsultConsultationListRouteImport.update({
    id: '/consultation-list',
    path: '/consultation-list',
    getParentRoute: () => AppConsultRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/oauth': typeof OauthRoute
  '/admin-excellent-cases': typeof AppAdminExcellentCasesRoute
  '/excellent-cases': typeof AppExcellentCasesRoute
  '/mypage': typeof AppMypageRoute
  '/consultation-list': typeof AppConsultConsultationListRoute
  '/consultation-result': typeof AppConsultConsultationResultRoute
  '/summary': typeof AppConsultSummaryRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/oauth': typeof OauthRoute
  '/': typeof AppIndexRoute
  '/admin-excellent-cases': typeof AppAdminExcellentCasesRoute
  '/excellent-cases': typeof AppExcellentCasesRoute
  '/mypage': typeof AppMypageRoute
  '/consultation-list': typeof AppConsultConsultationListRoute
  '/consultation-result': typeof AppConsultConsultationResultRoute
  '/summary': typeof AppConsultSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth': typeof OauthRoute
  '/_app/_consult': typeof AppConsultRouteWithChildren
  '/_app/admin-excellent-cases': typeof AppAdminExcellentCasesRoute
  '/_app/excellent-cases': typeof AppExcellentCasesRoute
  '/_app/mypage': typeof AppMypageRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_consult/consultation-list': typeof AppConsultConsultationListRoute
  '/_app/_consult/consultation-result': typeof AppConsultConsultationResultRoute
  '/_app/_consult/summary': typeof AppConsultSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/oauth'
    | '/admin-excellent-cases'
    | '/excellent-cases'
    | '/mypage'
    | '/consultation-list'
    | '/consultation-result'
    | '/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/oauth'
    | '/'
    | '/admin-excellent-cases'
    | '/excellent-cases'
    | '/mypage'
    | '/consultation-list'
    | '/consultation-result'
    | '/summary'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/oauth'
    | '/_app/_consult'
    | '/_app/admin-excellent-cases'
    | '/_app/excellent-cases'
    | '/_app/mypage'
    | '/_app/'
    | '/_app/_consult/consultation-list'
    | '/_app/_consult/consultation-result'
    | '/_app/_consult/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthRoute: typeof OauthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mypage': {
      id: '/_app/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof AppMypageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/excellent-cases': {
      id: '/_app/excellent-cases'
      path: '/excellent-cases'
      fullPath: '/excellent-cases'
      preLoaderRoute: typeof AppExcellentCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-excellent-cases': {
      id: '/_app/admin-excellent-cases'
      path: '/admin-excellent-cases'
      fullPath: '/admin-excellent-cases'
      preLoaderRoute: typeof AppAdminExcellentCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_consult': {
      id: '/_app/_consult'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppConsultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_consult/summary': {
      id: '/_app/_consult/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AppConsultSummaryRouteImport
      parentRoute: typeof AppConsultRoute
    }
    '/_app/_consult/consultation-result': {
      id: '/_app/_consult/consultation-result'
      path: '/consultation-result'
      fullPath: '/consultation-result'
      preLoaderRoute: typeof AppConsultConsultationResultRouteImport
      parentRoute: typeof AppConsultRoute
    }
    '/_app/_consult/consultation-list': {
      id: '/_app/_consult/consultation-list'
      path: '/consultation-list'
      fullPath: '/consultation-list'
      preLoaderRoute: typeof AppConsultConsultationListRouteImport
      parentRoute: typeof AppConsultRoute
    }
  }
}

interface AppConsultRouteChildren {
  AppConsultConsultationListRoute: typeof AppConsultConsultationListRoute
  AppConsultConsultationResultRoute: typeof AppConsultConsultationResultRoute
  AppConsultSummaryRoute: typeof AppConsultSummaryRoute
}

const AppConsultRouteChildren: AppConsultRouteChildren = {
  AppConsultConsultationListRoute: AppConsultConsultationListRoute,
  AppConsultConsultationResultRoute: AppConsultConsultationResultRoute,
  AppConsultSummaryRoute: AppConsultSummaryRoute,
}

const AppConsultRouteWithChildren = AppConsultRoute._addFileChildren(
  AppConsultRouteChildren,
)

interface AppRouteChildren {
  AppConsultRoute: typeof AppConsultRouteWithChildren
  AppAdminExcellentCasesRoute: typeof AppAdminExcellentCasesRoute
  AppExcellentCasesRoute: typeof AppExcellentCasesRoute
  AppMypageRoute: typeof AppMypageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConsultRoute: AppConsultRouteWithChildren,
  AppAdminExcellentCasesRoute: AppAdminExcellentCasesRoute,
  AppExcellentCasesRoute: AppExcellentCasesRoute,
  AppMypageRoute: AppMypageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthRoute: OauthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
