/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OauthRouteImport } from './routes/oauth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMypageRouteImport } from './routes/_app/mypage'
import { Route as AppConsultationListRouteImport } from './routes/_app/consultation-list'

const OauthRoute = OauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMypageRoute = AppMypageRouteImport.update({
  id: '/mypage',
  path: '/mypage',
  getParentRoute: () => AppRoute,
} as any)
const AppConsultationListRoute = AppConsultationListRouteImport.update({
  id: '/consultation-list',
  path: '/consultation-list',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/oauth': typeof OauthRoute
  '/consultation-list': typeof AppConsultationListRoute
  '/mypage': typeof AppMypageRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/oauth': typeof OauthRoute
  '/consultation-list': typeof AppConsultationListRoute
  '/mypage': typeof AppMypageRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth': typeof OauthRoute
  '/_app/consultation-list': typeof AppConsultationListRoute
  '/_app/mypage': typeof AppMypageRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/oauth' | '/consultation-list' | '/mypage'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/oauth' | '/consultation-list' | '/mypage' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/oauth'
    | '/_app/consultation-list'
    | '/_app/mypage'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthRoute: typeof OauthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/oauth': {
      id: '/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof OauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mypage': {
      id: '/_app/mypage'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof AppMypageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consultation-list': {
      id: '/_app/consultation-list'
      path: '/consultation-list'
      fullPath: '/consultation-list'
      preLoaderRoute: typeof AppConsultationListRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConsultationListRoute: typeof AppConsultationListRoute
  AppMypageRoute: typeof AppMypageRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConsultationListRoute: AppConsultationListRoute,
  AppMypageRoute: AppMypageRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthRoute: OauthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
